### PR TITLE
Fix MODE 2 Switch for Gamepad

### PR DESCRIPTION
**Pull request by retro-wertz**
-im new to this. if anyone can verify this does not affect anything else.

### CODE REVIEW

**Comment by twinaphex** [comment]
I don't think we have many users of this core, so as far as testing is concerned you're likely on your own. Spend a couple of days regression testing. If you can't find anything obvious, report back and we can merge it.

**Comment by Tatsuya79** [comment]
I'm not sure you need to change something in mednafen files.
Perhaps you can do it in libretro.cpp.

Tell me which game makes it easy to test that mode2 switch, I'd like to check it.

**Comment by retro-wertz** [comment]
i checked InputDeviceInputInfoStruct, and Mode2 is assigned "13", so made the change. although i still do not have a clue what games uses Mode2 Switch

mode2
thats the same text msg if was using standalone mednafen

**Comment by Tatsuya79** [comment]
Thanks, I haven't watch the log... lol

I found a way, it was my doubt when I made the previous buttons commit:
#13

**Pull request closed without merging**
